### ISSUE TITLE
Add color to text output

### ISSUE THREAD

**Issue by lamenezes** [grupy-sanca/dojo-toolkit#31]
To improve the usability all the text output should be colored. This was based on @douglasshimada #28 PR, thx!

Tests passed message could be green
Failed tests message red (only the header is red, the traceback and other details are "black")

This could be done using [colorama](https://github.com/tartley/colorama) lib that color texts from all operating systems.

Any other ideas?

**Comment by lamenezes** [comment]
We should usue this lib instead. It has many command-line utilities: https://github.com/kennethreitz/clint

**Comment by lamenezes** [comment]
Doing it

**Comment by zsinx6** [comment]
We this now: https://github.com/grupy-sanca/dojo-toolkit/pull/43
