### ISSUE TITLE
print notifications

### ISSUE THREAD

**Issue by lamenezes** [grupy-sanca/dojo-toolkit#47]
As dojo toolkit is implemented now informations such as time remaining, round finished etc. are only displayed on notifications. It might be a good idea to also display by printing it to the screen as an alternative.

**Comment by vccolombo** [comment]
Hey! Sorry but I didn't get what needs to be done

https://github.com/grupy-sanca/dojo-toolkit/blob/644cdebe9a1505c7633b1821777048609e133e4e/dojo_toolkit/dojo.py#L60-L70

It looks like it's already printing to the terminal. Is there something missing?

**Comment by lamenezes** [comment]
> It looks like it's already printing to the terminal. Is there something missing?

I guess the only way to be sure is to run the project locally and see if it's really printing those things. Have you done that?

**Comment by vccolombo** [comment]
[https://imgur.com/a/6o9BXgz](https://imgur.com/a/6o9BXgz)
[https://imgur.com/a/fLFxUDr](https://imgur.com/a/fLFxUDr)

Is this everything that needs to be printing?

**Comment by lamenezes** [comment]
That's pretty much it. Thanks for the print screens @vccolombo! They also revealed another bug: on the first image the errors are displayed as the representation of a binary instead of a text, i.e.: it's `b'string'` and should be only `string`.

I'll be closing this issue and opening another one. Feel free to take other issues @vccolombo and thanks again :tada: :burrito: :rescue_worker_helmet:
