### ISSUE TITLE
shows time for the last 1 minute (mostrar tempo quando faltar 1 minuto para acabar)

### ISSUE THREAD

**Issue by douglasshimada** [grupy-sanca/dojo-toolkit#5]

**Comment by zsinx6** [comment]
Lets keep it in english, at least for the simple things, maybe put in pt-br if necessary such as long conversations about new ideas and some implementation problems, but english is always better, even if is bad english

**Comment by douglasshimada** [comment]
Vou fazer

**Comment by lamenezes** [comment]
Solved
