### ISSUE TITLE
sound on notifications (Colocar som nas notificações)

### ISSUE THREAD

**Issue by douglasshimada** [grupy-sanca/dojo-toolkit#9]

**Comment by zsinx6** [comment]
ideas about which sound use? preferred free sounds

**Comment by douglasshimada** [comment]
Don't know. Will we use sound on all notifications?
LOL. I think these two are great to use when the tests fail: https://www.freesound.org/people/pyro13djt/sounds/331911/ or https://www.freesound.org/people/11linda/sounds/234035/
Time Up: https://www.freesound.org/people/rparson/sounds/104475/
Test ok: https://www.freesound.org/people/Artmasterrich/sounds/345465/

**Comment by lamenezes** [comment]
This one would be nice to play when a round starts: http://soundbible.com/2148-Chinese-Gong.html

**Comment by douglasshimada** [comment]
@lamenezes 
Chinese gong is really cool when a round starts. xD

**Comment by zsinx6** [comment]
Does the test fail really needs a sound? When pass its is great, on time up is very necessary, on start its is cool, but on fail I don't know. Rount start and passing from @lamenezes and time up from @douglasshimada are the best
